第3回課題 List、Map、例外処理を実装してみよう
aoha968/Java2211 pull request #3
Opened 2022-11-23 02:15 UTC by aoha968

第3回課題 List、Map、例外処理を実装してみよう
以下のプログラムを実装しました。
・String型のListを使用して手持ちポケモンを表示する
・String型のMapを使用してポケモンの図鑑説明を表示する
・想定外の入力をされたら例外処理を実施する

2022-11-23 02:25 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-11-23 02:25 UTC, YudaiNoda3576 commented on lecture03/List_Map/src/Main.java
> +            pokemonList.forEach(System.out::println);
streamもメソッド参照も使えていてすごい！！！

2022-11-23 02:25 UTC, YudaiNoda3576 commented on lecture03/List_Map/src/Main.java
> +            System.out.println("*** ７匹目のポケモンを表示させる ***");
tryブロックはここから始めるで良いと思います！

2022-11-23 02:25 UTC, YudaiNoda3576 commented on lecture03/List_Map/src/Main.java
> +            System.out.println("*** 未知のポケモンの図鑑説明を表示させる ***");
ここもtryブロックはここから始めるで良さそうです！

2022-11-23 02:25 UTC, YudaiNoda3576 commented on lecture03/List_Map/src/UnKnownPokemonException.java
> +    UnKnownPokemonException(String code, String message) {
空白行いれておきましょう！

2022-11-23 04:05 UTC, TomooAkamatsu commented on lecture03/List_Map/src/Main.java
> +        HashMap<String, String> pokemon = new HashMap<>();
ここもMapで受け取ってしまっていいと思います！

2022-11-23 04:39 UTC, aoha968 commented
コメントを確認＆検討し、対策を入れました。

2022-11-24 02:40 UTC, YudaiNoda3576 commented
![LGTM](https://images.lgtmgen.org/62da321c-89b2-446e-972c-2de51561dcd5)

2022-11-24 12:22 UTC, merged